### ISSUE TITLE
Find errors

### ISSUE THREAD

**Issue by IgorDePaula** [mgechev/angular-vnc#1]
igor@igor-GA-78LMT-USB3 ~/Downloads/angular-vnc-master/client$ grunt
Running "newer:jshint" (newer) task

Running "newer:jshint:all" (newer) task

Running "jshint:all" (jshint) task

app/scripts/app.js
  line 14   col 5   Missing semicolon.

app/scripts/controllers/main.js
  line 17   col 33  Missing semicolon.

app/scripts/directives/vnc-screen.js
  line 87   col 29  Did you mean to return a conditional instead of an assignment?
  line 94   col 31  Did you mean to return a conditional instead of an assignment?
  line 143  col 50  'attrs' is defined but never used.

app/scripts/services/io.js
  line 6    col 14  'io' is not defined.
  line 6    col 31  'io' is not defined.

app/scripts/services/vncclient.js
  line 35   col 7   Expected '{' and instead saw 'this'.
  line 89   col 7   Expected '{' and instead saw 'if'.
  line 89   col 16  Expected '===' and instead saw '=='.
  line 90   col 9   Expected '{' and instead saw 'return'.
  line 79   col 39  'success' is defined but never used.

✖ 12 problems

Warning: Task "jshint:all" failed. Use --force to continue.

Aborted due to warnings.

Execution Time (2015-02-21 13:05:52 UTC)
loading tasks       3ms  ▇ 2%
newer:jshint        2ms  ▇ 1%
newer:jshint:all    3ms  ▇ 2%
jshint:all        188ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 96%
Total 196ms

On server, he don't load javascript dependencies

**Comment by mgechev** [comment]
Thanks! These jshint errors are annoying. Should be fixed now.

**Comment by karthickraja07** [comment]
when trying to connect to the raspberry pi system getting below error "Error while talking with the remote RFB server".
How can I resolve this one please help?
