### ISSUE TITLE
How could we run this with Angular 8

### ISSUE THREAD

**Issue by Dali2579** [mgechev/angular-vnc#2]
Is it possible to integrate this with an Angular 8 application?

**Comment by narkhedek3** [comment]
> Is it possible to integrate this with an Angular 8 application?

Hi, Have you found any solution to implement it on a newer angular version..?

**Comment by mgechev** [comment]
VNC is not coupled to Angular in anyway. If you extract the client-side logic you should be easily migrate it to Angular from AngularJS.
